
import React, { useState, useEffect, useCallback } from 'react';
import { supabase } from '../../lib/supabaseClient';
import { TrashIcon, CogIcon, ClipboardCopyIcon } from '../Icons';

interface Submission {
    id: number;
    created_at: string;
    name: string;
    email: string;
    subject: string;
    message: string;
}

const SETUP_SQL = `
-- Run this SQL in your Supabase SQL Editor to create the contact_submissions table

-- 1. Create the table
create table if not exists public.contact_submissions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text,
  email text,
  subject text,
  message text
);

-- 2. Enable Row Level Security
alter table public.contact_submissions enable row level security;

-- 3. Allow public access to insert data
create policy "Enable insert for all users" 
on public.contact_submissions for insert 
with check (true);

-- 4. Allow authenticated users (admin) to view data
create policy "Enable read access for authenticated users only" 
on public.contact_submissions for select 
using (auth.role() = 'authenticated');

-- 5. Allow authenticated users (admin) to delete data
create policy "Enable delete for authenticated users only" 
on public.contact_submissions for delete 
using (auth.role() = 'authenticated');
`;

const ContactSubmissions: React.FC = () => {
    const [submissions, setSubmissions] = useState<Submission[]>([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);
    const [showSetup, setShowSetup] = useState(false);

    const fetchSubmissions = useCallback(async () => {
        setLoading(true);
        setError(null);
        const { data, error } = await supabase
            .from('contact_submissions')
            .select('*')
            .order('created_at', { ascending: false });

        if (error) {
            console.error('Error fetching submissions:', error);
            if (error.code === '42P01' || error.message.includes('does not exist')) {
                setShowSetup(true);
                setError('The database table for contact submissions is missing.');
            } else {
                setError('Failed to load submissions. ' + error.message);
            }
        } else {
            setSubmissions(data || []);
        }
        setLoading(false);
    }, []);

    useEffect(() => {
        fetchSubmissions();
    }, [fetchSubmissions]);

    const handleDelete = async (id: number) => {
        if (window.confirm('Are you sure you want to delete this submission? This action cannot be undone.')) {
            const { error } = await supabase
                .from('contact_submissions')
                .delete()
                .eq('id', id);
            
            if (error) {
                console.error('Error deleting submission:', error);
                setError(`Failed to delete submission: ${error.message}`);
            } else {
                fetchSubmissions(); // Refresh the list
            }
        }
    };

    const copySql = () => {
        navigator.clipboard.writeText(SETUP_SQL);
        alert('SQL copied to clipboard! Run this in your Supabase SQL Editor.');
    };

    if (showSetup) {
        return (
            <div className="space-y-6">
                <div className="flex justify-between items-center">
                    <h2 className="text-2xl font-bold text-gray-800">Database Setup: Contact Forms</h2>
                    <button onClick={() => setShowSetup(false)} className="text-gray-600 hover:text-gray-900 font-semibold">
                        Back to Submissions
                    </button>
                </div>
                
                <div className="bg-white p-6 rounded-lg shadow-sm border border-gray-200">
                    <h3 className="text-lg font-bold text-gray-800 mb-4">SQL Setup Instructions</h3>
                    <p className="mb-4 text-gray-600 text-sm">
                        To capture contact form submissions, run the following SQL in your Supabase project. <br/>
                    </p>
                    <ol className="list-decimal list-inside mb-6 text-sm text-gray-700 space-y-2">
                        <li>Go to your <strong>Supabase Project Dashboard</strong>.</li>
                        <li>Open the <strong>SQL Editor</strong> from the left sidebar.</li>
                        <li>Click <strong>"New Query"</strong>.</li>
                        <li>Copy and paste the SQL code below.</li>
                        <li>Click <strong>"Run"</strong>.</li>
                    </ol>
                    <div className="relative">
                        <pre className="bg-gray-900 text-gray-100 p-4 rounded-md overflow-x-auto text-xs leading-relaxed font-mono">
                            {SETUP_SQL}
                        </pre>
                        <button 
                            onClick={copySql}
                            className="absolute top-2 right-2 bg-white/10 hover:bg-white/20 text-white p-2 rounded transition-colors flex items-center gap-2 text-xs font-bold border border-white/20"
                        >
                            <ClipboardCopyIcon className="h-4 w-4" /> Copy SQL
                        </button>
                    </div>
                    <div className="mt-6 flex justify-end">
                         <button 
                            onClick={fetchSubmissions}
                            className="bg-[#8C1E1E] text-white px-6 py-2 rounded-md hover:bg-[#7a1a1a] font-semibold shadow-md transition-transform active:scale-95"
                        >
                            I've run the SQL, Refresh Page
                        </button>
                    </div>
                </div>
            </div>
        );
    }
    
    return (
        <div className="space-y-6">
            <div className="flex justify-between items-center">
                <h2 className="text-2xl font-bold text-gray-800">Contact Form Submissions</h2>
                 <button 
                    onClick={() => setShowSetup(true)} 
                    className="flex items-center gap-2 text-sm text-gray-600 hover:text-[#8C1E1E] border border-gray-300 px-3 py-1.5 rounded bg-white hover:bg-gray-50 transition-colors"
                >
                    <CogIcon className="h-4 w-4" /> View Database Schema
                </button>
            </div>

            {error && <p className="text-sm text-red-600 bg-red-100 p-3 rounded-md">{error}</p>}

            <div className="bg-white p-6 rounded-lg shadow-sm border border-gray-200">
                {loading ? <p>Loading submissions...</p> : (
                    submissions.length === 0 ? <p className="text-gray-500">No submissions yet.</p> : (
                        <div className="space-y-4">
                            {submissions.map(sub => (
                                <div key={sub.id} className="border border-gray-200 rounded-lg p-4">
                                    <div className="flex justify-between items-start">
                                        <div>
                                            <p className="font-bold text-gray-800">{sub.name} <span className="font-normal text-gray-500">&lt;{sub.email}&gt;</span></p>
                                            <p className="text-sm text-gray-500">{new Date(sub.created_at).toLocaleString()}</p>
                                            <p className="text-sm font-semibold text-gray-600 mt-2">Subject: {sub.subject}</p>
                                        </div>
                                        <button 
                                            onClick={() => handleDelete(sub.id)}
                                            className="text-[#8C1E1E] hover:text-[#7a1a1a] p-1"
                                            title="Delete Submission"
                                        >
                                            <TrashIcon className="h-5 w-5" />
                                        </button>
                                    </div>
                                    <p className="mt-3 text-gray-700 bg-gray-50 p-3 rounded-md whitespace-pre-wrap">{sub.message}</p>
                                </div>
                            ))}
                        </div>
                    )
                )}
            </div>
        </div>
    );
};

export default ContactSubmissions;
