
import React, { useState, useEffect, useCallback } from 'react';
import { supabase } from '../../lib/supabaseClient';
import { TrashIcon, EyeIcon, ClipboardCopyIcon, CogIcon } from '../Icons';

interface IntakeSubmission {
    id: number;
    created_at: string;
    first_name: string;
    last_name: string;
    email: string;
    phone: string;
    age: string;
    fitness_level: string;
    goals: string;
    injuries: string;
    availability: string[];
    preferred_service: string;
    budget: string;
    additional_info: string;
}

const SETUP_SQL = `
-- Run this SQL in your Supabase SQL Editor to create the necessary table

-- 1. Create the intake_submissions table
create table if not exists public.intake_submissions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  first_name text,
  last_name text,
  email text,
  phone text,
  age text, -- stored as text to handle any input format
  fitness_level text,
  goals text,
  injuries text,
  availability text[], -- array of strings for multiple checkbox selection
  preferred_service text,
  budget text,
  additional_info text
);

-- 2. Enable Row Level Security
alter table public.intake_submissions enable row level security;

-- 3. Allow public access to insert data (for the public form)
create policy "Enable insert for all users" 
on public.intake_submissions for insert 
with check (true);

-- 4. Allow authenticated users (admin) to view data
create policy "Enable read access for authenticated users only" 
on public.intake_submissions for select 
using (auth.role() = 'authenticated');

-- 5. Allow authenticated users (admin) to delete data
create policy "Enable delete for authenticated users only" 
on public.intake_submissions for delete 
using (auth.role() = 'authenticated');
`;

const IntakeSubmissions: React.FC = () => {
    const [submissions, setSubmissions] = useState<IntakeSubmission[]>([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);
    const [missingTable, setMissingTable] = useState(false);
    const [selectedSubmission, setSelectedSubmission] = useState<IntakeSubmission | null>(null);
    const [showSetup, setShowSetup] = useState(false);

    const fetchSubmissions = useCallback(async () => {
        setLoading(true);
        setError(null);
        setMissingTable(false);
        const { data, error } = await supabase
            .from('intake_submissions')
            .select('*')
            .order('created_at', { ascending: false });

        if (error) {
            console.error('Error fetching intake submissions:', error);
            // Check for table missing (42P01) or other relation errors
            if (error.code === '42P01' || error.message.includes('does not exist')) {
                setMissingTable(true);
                setError('The database table for intake submissions is missing.');
                setShowSetup(true);
            } else {
                setError('Failed to load submissions. ' + error.message);
            }
        } else {
            setSubmissions(data || []);
        }
        setLoading(false);
    }, []);

    useEffect(() => {
        fetchSubmissions();
    }, [fetchSubmissions]);

    const handleDelete = async (id: number) => {
        if (window.confirm('Are you sure you want to delete this submission? This action cannot be undone.')) {
            const { error } = await supabase
                .from('intake_submissions')
                .delete()
                .eq('id', id);
            
            if (error) {
                console.error('Error deleting submission:', error);
                setError(`Failed to delete submission: ${error.message}`);
            } else {
                fetchSubmissions(); // Refresh the list
                if (selectedSubmission?.id === id) setSelectedSubmission(null);
            }
        }
    };
    
    const copySql = () => {
        navigator.clipboard.writeText(SETUP_SQL);
        alert('SQL copied to clipboard! Run this in your Supabase SQL Editor.');
    };

    if (showSetup || missingTable) {
        return (
            <div className="space-y-6">
                <div className="flex justify-between items-center">
                    <h2 className="text-2xl font-bold text-gray-800">Database Setup: Intake Forms</h2>
                    {!missingTable && (
                        <button onClick={() => setShowSetup(false)} className="text-gray-600 hover:text-gray-900 font-semibold">
                            Back to Submissions
                        </button>
                    )}
                </div>

                {missingTable && (
                    <div className="bg-yellow-50 border-l-4 border-yellow-400 p-4 rounded-md shadow-sm">
                        <div className="flex">
                            <div className="flex-shrink-0">
                                <CogIcon className="h-5 w-5 text-yellow-400" />
                            </div>
                            <div className="ml-3">
                                <h3 className="text-sm leading-5 font-medium text-yellow-800">
                                    Database Table Missing
                                </h3>
                                <div className="mt-2 text-sm leading-5 text-yellow-700">
                                    <p>The <code>intake_submissions</code> table has not been created yet. Please run the SQL below.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                )}
                
                <div className="bg-white p-6 rounded-lg shadow-sm border border-gray-200">
                    <h3 className="text-lg font-bold text-gray-800 mb-4">SQL Setup Instructions</h3>
                    <p className="mb-4 text-gray-600 text-sm">
                        To capture intake form submissions, run the following SQL in your Supabase project. <br/>
                    </p>
                    <ol className="list-decimal list-inside mb-6 text-sm text-gray-700 space-y-2">
                        <li>Go to your <strong>Supabase Project Dashboard</strong>.</li>
                        <li>Open the <strong>SQL Editor</strong> from the left sidebar.</li>
                        <li>Click <strong>"New Query"</strong>.</li>
                        <li>Copy and paste the SQL code below.</li>
                        <li>Click <strong>"Run"</strong>.</li>
                    </ol>
                    <div className="relative">
                        <pre className="bg-gray-900 text-gray-100 p-4 rounded-md overflow-x-auto text-xs leading-relaxed font-mono">
                            {SETUP_SQL}
                        </pre>
                        <button 
                            onClick={copySql}
                            className="absolute top-2 right-2 bg-white/10 hover:bg-white/20 text-white p-2 rounded transition-colors flex items-center gap-2 text-xs font-bold border border-white/20"
                        >
                            <ClipboardCopyIcon className="h-4 w-4" /> Copy SQL
                        </button>
                    </div>
                    <div className="mt-6 flex justify-end">
                         <button 
                            onClick={fetchSubmissions}
                            className="bg-[#8C1E1E] text-white px-6 py-2 rounded-md hover:bg-[#7a1a1a] font-semibold shadow-md transition-transform active:scale-95"
                        >
                            {missingTable ? "I've run the SQL, Check Connection" : "Refresh Data"}
                        </button>
                    </div>
                </div>
            </div>
        );
    }
    
    return (
        <div className="space-y-6">
            <div className="flex justify-between items-center">
                <h2 className="text-2xl font-bold text-gray-800">Intake Form Submissions</h2>
                <button 
                    onClick={() => setShowSetup(true)} 
                    className="flex items-center gap-2 text-sm text-gray-600 hover:text-[#8C1E1E] border border-gray-300 px-3 py-1.5 rounded bg-white hover:bg-gray-50 transition-colors"
                >
                    <CogIcon className="h-4 w-4" /> View Database Schema
                </button>
            </div>

            {error && <p className="text-sm text-red-600 bg-red-100 p-3 rounded-md">{error}</p>}

            <div className="grid lg:grid-cols-3 gap-6">
                <div className="lg:col-span-1 bg-white p-4 rounded-lg shadow-sm border border-gray-200 h-[calc(100vh-200px)] overflow-y-auto">
                     {loading ? <p>Loading...</p> : (
                        submissions.length === 0 ? <p className="text-gray-500 text-center py-4">No submissions yet.</p> : (
                            <ul className="space-y-2">
                                {submissions.map(sub => (
                                    <li 
                                        key={sub.id} 
                                        onClick={() => setSelectedSubmission(sub)}
                                        className={`p-3 rounded-md cursor-pointer border transition-colors ${selectedSubmission?.id === sub.id ? 'bg-blue-50 border-blue-300' : 'hover:bg-gray-50 border-transparent'}`}
                                    >
                                        <p className="font-bold text-gray-800">{sub.first_name} {sub.last_name}</p>
                                        <p className="text-xs text-gray-500">{sub.preferred_service}</p>
                                        <p className="text-xs text-gray-400 mt-1">{new Date(sub.created_at).toLocaleDateString()}</p>
                                    </li>
                                ))}
                            </ul>
                        )
                    )}
                </div>

                <div className="lg:col-span-2 bg-white p-6 rounded-lg shadow-sm border border-gray-200 h-[calc(100vh-200px)] overflow-y-auto">
                    {selectedSubmission ? (
                        <div>
                            <div className="flex justify-between items-start mb-6 border-b pb-4">
                                <div>
                                    <h3 className="text-xl font-bold text-gray-900">{selectedSubmission.first_name} {selectedSubmission.last_name}</h3>
                                    <p className="text-gray-600">{selectedSubmission.email} • {selectedSubmission.phone}</p>
                                    <p className="text-sm text-gray-400 mt-1">Submitted: {new Date(selectedSubmission.created_at).toLocaleString()}</p>
                                </div>
                                <button 
                                    onClick={() => handleDelete(selectedSubmission.id)}
                                    className="text-red-500 hover:text-red-700 p-2 rounded-md hover:bg-red-50 transition-colors flex items-center"
                                >
                                    <TrashIcon className="h-5 w-5 mr-1" /> Delete
                                </button>
                            </div>
                            
                            <div className="space-y-6">
                                <div className="grid grid-cols-2 gap-4">
                                    <div className="p-3 bg-gray-50 rounded-md">
                                        <p className="text-xs font-bold text-gray-500 uppercase">Age</p>
                                        <p className="text-gray-800">{selectedSubmission.age}</p>
                                    </div>
                                    <div className="p-3 bg-gray-50 rounded-md">
                                        <p className="text-xs font-bold text-gray-500 uppercase">Fitness Level</p>
                                        <p className="text-gray-800">{selectedSubmission.fitness_level}</p>
                                    </div>
                                     <div className="p-3 bg-gray-50 rounded-md">
                                        <p className="text-xs font-bold text-gray-500 uppercase">Preferred Service</p>
                                        <p className="text-gray-800">{selectedSubmission.preferred_service}</p>
                                    </div>
                                     <div className="p-3 bg-gray-50 rounded-md">
                                        <p className="text-xs font-bold text-gray-500 uppercase">Budget</p>
                                        <p className="text-gray-800">{selectedSubmission.budget}</p>
                                    </div>
                                </div>

                                <div>
                                    <p className="text-sm font-bold text-gray-700 mb-2">Goals</p>
                                    <p className="p-3 bg-gray-50 rounded-md text-gray-800 whitespace-pre-wrap">{selectedSubmission.goals}</p>
                                </div>

                                <div>
                                    <p className="text-sm font-bold text-gray-700 mb-2">Injuries / Limitations</p>
                                    <p className="p-3 bg-gray-50 rounded-md text-gray-800 whitespace-pre-wrap">{selectedSubmission.injuries || 'None reported'}</p>
                                </div>

                                <div>
                                    <p className="text-sm font-bold text-gray-700 mb-2">Availability</p>
                                    <div className="flex flex-wrap gap-2">
                                        {selectedSubmission.availability && Array.isArray(selectedSubmission.availability) ? (
                                            selectedSubmission.availability.map((time, i) => (
                                                <span key={i} className="bg-blue-100 text-blue-800 text-xs px-2 py-1 rounded-full font-medium">{time}</span>
                                            ))
                                        ) : (
                                            <p className="text-gray-500 italic">No availability selected</p>
                                        )}
                                    </div>
                                </div>

                                <div>
                                    <p className="text-sm font-bold text-gray-700 mb-2">Additional Info</p>
                                    <p className="p-3 bg-gray-50 rounded-md text-gray-800 whitespace-pre-wrap">{selectedSubmission.additional_info || 'None'}</p>
                                </div>
                            </div>
                        </div>
                    ) : (
                        <div className="h-full flex flex-col items-center justify-center text-gray-400">
                            <EyeIcon className="h-12 w-12 mb-2 opacity-50" />
                            <p>Select a submission to view details</p>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
};

export default IntakeSubmissions;
